import type { Metadata } from "next"
import "./yay.css"
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar"
import { YaySidebar } from "./_components/yay-sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SidebarProvider>
      <YaySidebar />
      <SidebarInset>{children}</SidebarInset>
    </SidebarProvider>
  )
}
