import type { Metadata } from "next"
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar"
import "./shadcn.css"
import { ShadcnSidebar } from "./_components/shadcn-sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SidebarProvider>
      <ShadcnSidebar />
      <SidebarInset>{children}</SidebarInset>
    </SidebarProvider>
  )
}
